name: Deploy to npm 

on:
  push:
    branches:
      - main 
      - beta
      - alpha

jobs:
  deploy:
    name: Deploy to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci 
      
      - name: Compile 
        run: npm run compile 
      - name: Generate docs 
        run: npm run docs 
      - name: Deploy via semantic release 
        uses: cycjimmy/semantic-release-action@v2
        with: 
          # version numbers below can be in many forms: M, M.m, M.m.p
          semantic_version: 17
          extra_plugins: |
            @semantic-release/commit-analyzer@8
            @semantic-release/release-notes-generator@9
            @semantic-release/changelog@5
            @semantic-release/npm@7
            @semantic-release/git@9
            @semantic-release/github@7
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PUSH_TOKEN }}        
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 
          
