name: Test
# only run on PRs and when push a commit on a branch that we don't deploy on. 
on: 
  push:
    # NOTE: We are enabling testing on all branches because we want codecov to generate a report on that branch so we have something to compare to. 
    branches: 
      - '*'
    tags-ignore: # Don't run tests on tags as tags are made off of master branch. 
      - '*'
  pull_request: # Run on all PRs. 
    branches:
      - '*'

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test:
    name: Automated tests 
    runs-on: ubuntu-latest
    # skip if '[skip ci]' exists in commit message 
    if: ${{ !contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[skip ci]') }}
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NODE_VERSION }}'
      - name: Install dependencies
        run: npm ci 
      - name: Test compile works 
        run: npm run compile 
      - name: Run tests 
        run:  npm run test && npx codecov